project_id = "vpexxhfpvghlejljwpvt"

[functions.github-roadmap]
verify_jwt = false

[functions.create-github-issue]
verify_jwt = false

[functions.nih-grants]
verify_jwt = false

[functions.ner-extract]
verify_jwt = false
